openapi: 3.0.3
info:
  title: Betta APIs
  description: |-
    Backend API designs
  version: 1.0.0

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login and get the JWT Authorization Token
      description: Use the Authorization Token in "Authorization" Header with "Bear " Prefix
      operationId: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "zayarhtet@gmail.com"
                password:
                  type: string
                  example: "Password123"
      responses:
        "200":
          description: Login success
        "400":
          description: Wrong Password
        "404":
          description: User not found
        "406":
          description: Validation Error
        "500":
          description: Internal Server Error

  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: Register a new user
      operationId: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "zayarhtet@gmail.com"
                password:
                  type: string
                  example: "Password123"
      responses:
        "200":
          description: Login success
        "400":
          description: Email already exists
        "406":
          description: Validation Error
        "500":
          description: Internal Server Error

  /auth/refresh-token:
    post:
      tags:
        - Auth
      summary: Get newly generated token
      description: Get newly generated token
      operationId: Refresh Token
      requestParam:

      responses:
        "200":
          description: Login success
        "500":
          description: Internal Server Error

  /auth/logout:
    post:
      tags:
        - Auth
      summary: Get newly generated logout token
      description: Get newly generated logout token
      operationId: Logout
      requestParam:

      responses:
        "200":
          description: Logout Success
        "500":
          description: Internal Server Error

  /auth/who-am-i:
    post:
      tags:
        - Auth
      summary: Get Logged-in User
      description: Get Logged-in User
      operationId: Who Am I
      requestParam:

      responses:
        "200":
          description: User Details
        "500":
          description: Internal Server Error

  /auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Forgot Password
      description: Forgot Password
      operationId: Forgot Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "zayarhtet20152015@gmail.com"

      responses:
        "200":
          description: OTP Email Sent
        "404":
          description: User not found
        "500":
          description: Internal Server Error

  /auth/verify-otp:
    post:
      tags:
        - Auth
      summary: Verify OTP
      description: Verify OTP
      operationId: Verify OTP
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "zayarhtet20152015@gmail.com"
                otp:
                  type: string
                  example: "1234"
      responses:
        "200":
          description: OTP Verified
        "400":
          description: OTP Expired
        "404":
          description: User not found
        "500":
          description: Internal Server Error

  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset Password  **(Need Authorization Token From Verify OTP)**
      description: Reset Password
      operationId: Reset Password

      security:
        - bearerAuth: []
      requestHeader:
        Authorization:
          type: string
          example: "Bearer {token}"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: "Password123"
                confirmPassword:
                  type: string
                  example: "Password123"
      responses:
        "200":
          description: Password Reset Success
        "404":
          description: User not found
        "500":
          description: Internal Server Error
